name: Test workflow
on:
  - push
jobs:
  install:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'pnpm'
      - run: pnpm install

  unit-testing:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'pnpm'
      - run: pnpm install
      - name: Run tests
        run: pnpm test

  e2e-testing:
    runs-on: ubuntu-20.04
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'pnpm'
      - run: pnpm install
      - name: E2E Testing
        uses: cypress-io/github-action@v2
        with:
          install: false
          build: pnpm build
          start: pnpm start
          wait-on: 'http://localhost:3000'